- hosts: webservers
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - install_docker
    - install_docker_compose
    - { role: install_nginx, tags: ['install_nginx_role'] }
    - nginx_change_port # this will change nginx from 80 to 81
